### ISSUE TITLE
Python 2.7 support broken

### ISSUE THREAD

**Issue by robert-scheck** [bontchev/pcodedmp#15]
It seems like the Python 2.7 support is broken, happening on RHEL/CentOS 7:

```
/usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
error in pcodedmp setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

In case this is intended, please remove mentioning of Python 2.6+ support in `README.md`.

**Comment by bontchev** [comment]
`pcodedmp` works with Python 2.7 just fine - in fact, this is precisely how I am using it.

It seems that CentOS doesn't like something in the installation script - not in `pcodedmp` itself.

Regarding the warning, `long_description_content_type` is a perfectly valid flag as you can see from the [documentation](https://packaging.python.org/guides/making-a-pypi-friendly-readme/).

Regarding the error, `install_requires` _is_ a list of strings containing valid project/version specifiers:

```
INSTALL_REQUIRES = [
    'oletools>=0.54',
    'win_unicode_console; platform_system=="Windows" and platform_python_implementation!="PyPy"',
]
```

My _guess_ is that something is wrong with CentOS' setup package and it doesn't parse properly the second element of the list. Since this element specifies a package that should be installed on Windows only anyway and you aren't using that OS, try removing this element from the list.

**Comment by robert-scheck** [comment]
Looks like the version of Python setuptools in RHEL/CentOS 7 is too old for this syntax.
