### ISSUE TITLE
Redundant parens in README sample code

### ISSUE THREAD

**Issue by wqweto** [bontchev/pcodedmp#20]
Btw, this line in VBA
```
        Shell ("calc.exe")
```
is similar to this line in C/C++
```
        printf(("Hello %s"), ("World"));
```
with redundant parens around the string literals.

Unfortunately it's already compiled in a (redundant) `Paren` p-code here
```
        LitStr 0x0008 "calc.exe"
        Paren
        ArgsCall Shell 0x0001
```

Also notice that VBA IDE always puts a space between `Shell` and the argument so the README is faking it by manually removing the space in this line
```
        Shell("calc.exe")
```
which is obviously not a verbatim copy/paste from the VBA IDE.

**Comment by bontchev** [comment]
The parentheses are indeed redundant in this case, as far as VBA is concerned. But since they have been used in the example VBA code, they have resulted in the `Paren` p-code instruction being compiled, so I'm keeping both.

I have added the missing space to the `README` file in the `develop` branch.
